#!/bin/bash
./main -sandbox "{reference_image {image:s = \"ref21.jpg\" background_color:p3 = 1, 1, 1}}" 
./main -sandbox "{reference_image {image:s = \"ref22.png\" background_color:p3 = 0, 0, 0}}" 
./main -sandbox "{reference_image {image:s = \"ref23.jpg\" background_color:p3 = 1, 1, 1}}"
./main -sandbox "{reference_image {image:s = \"ref24.jpg\" background_color:p3 = 1, 1, 1}}" 
./main -sandbox "{reference_image {image:s = \"ref10.png\" background_color:p3 = 0, 0, 0}}" 
./main -sandbox "{reference_image {image:s = \"ref11.png\" background_color:p3 = 0, 0, 0}}"
./main -sandbox "{reference_image {image:s = \"ref25.png\" background_color:p3 = 0, 0, 0}}" 
./main -sandbox "{reference_image {image:s = \"ref26.jpg\" background_color:p3 = 1, 1, 1}}" 
./main -sandbox "{reference_image {image:s = \"ref27.jpg\" background_color:p3 = 1, 1, 1}}"  