#version 460
#extension GL_GOOGLE_include_directive : require

#include "common_gpu.h"

layout(binding = 0, set = 0) buffer data0 { float data[]; }; //
layout(binding = 1, set = 0) buffer dataUBO { TensorProcessorImpl_GPU_UBO_Data ubo; };

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout( push_constant ) uniform kernelArgs
{
  Variable A;
  uint seed;
  uint iNumElementsX; 
  uint steps; 
  uint iNumElementsZ; 
  uint tFlagsMask;    
} kgenArgs;


void main()
{
  bool runThisThread = true;
  ///////////////////////////////////////////////////////////////// prolog
  const uint i = uint(gl_GlobalInvocationID[0]); 
  if(i >= kgenArgs.iNumElementsX + 0)
    runThisThread = false;
    ///////////////////////////////////////////////////////////////// prolog
  if(runThisThread)
  {
  
    uint n = kgenArgs.seed + i;
    n = (n << 13) ^ n; 
    data[kgenArgs.A.offset + i] = float((n * (n*n*15731+789221) + 1376312589) & 0x3fffffff) / float(0x3fffffff);
  
  }
}

