#version 460
#extension GL_GOOGLE_include_directive : require

#include "common_gpu.h"

layout(binding = 0, set = 0) buffer data0 { float data[]; }; //
layout(binding = 1, set = 0) buffer dataUBO { TensorProcessorImpl_GPU_UBO_Data ubo; };

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

layout(local_size_x = 32, local_size_y = 8, local_size_z = 1) in;

layout( push_constant ) uniform kernelArgs
{
  uint B_outer_step;
  uint B_inner_step;
  Variable A;
  Variable B;
  Variable C;
  uint step_size; 
  uint steps; 
  uint iNumElementsZ; 
  uint tFlagsMask;    
} kgenArgs;


void main()
{
  bool runThisThread = true;
  ///////////////////////////////////////////////////////////////// prolog
  const uint j = uint(gl_GlobalInvocationID[0]); 
  const uint i = uint(gl_GlobalInvocationID[1]); 
  if(j >= kgenArgs.step_size + 0 || i >= kgenArgs.steps + 0)
    runThisThread = false;
    ///////////////////////////////////////////////////////////////// prolog
  if(runThisThread)
  {
  data[kgenArgs.C.offset + i * kgenArgs.step_size + j] = data[kgenArgs.A.offset + i * kgenArgs.step_size + j] * data[kgenArgs.B.offset + i * kgenArgs.B_outer_step + kgenArgs.B_inner_step * j];
  }
}

