#pragma once
enum GenerationTask
{
    GENERATE = 1,
    CLUSTERIZE = 2,
    BILLBOARDS = 4,
    IMPOSTORS = 8,
    IMPOSTOR_FULL_GROVE = 16,
    SYNTS = 32,
    MODELS = 64
};
#define ALL_GENERATION_TASKS (2*MODELS - 1)
#define MINIMUM_FOR_RENDER (GENERATE|CLUSTERIZE|MODELS)