#version 430
#define THREADS 1
layout( local_size_x = THREADS ) in;


layout(std140, binding=8) writeonly buffer _curTypes
{
    uvec4 curTypes[];
};

uniform uint count;

void main()
{
    uint cnt = count / THREADS + 1;
    uint st, en;
    st = cnt * gl_LocalInvocationIndex;
    en = cnt * (gl_LocalInvocationIndex + 1);

    en = en > count ? count : en;

    for (uint i = st; i < en; i++)
    {
        curTypes[i] = uvec4(0);
    }
}
