#version 430

layout( local_size_x = 1, local_size_y = 1) in;

layout(rgba32f, binding = 5) readonly uniform image2D uv;

layout(rgba32f, binding = 6) writeonly uniform image2D tex;

uniform sampler2D photo;

void main()
{
    vec2 coord = gl_GlobalInvocationID.xy;
    if (texture(uv,coord).b == 0)
    {
        return;
    }
    vec2 uv_coords = texture(uv,coord).rg;
    tex[uv_coords.x][uv_coords.y] = texture(photo, coord);
}
